# Generated by Django 3.1.14 on 2025-02-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20250207_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disapeared_at',
            new_name='disappeared_at',
        ),
    ]
